### ISSUE TITLE
ValueError:  not found in any keyboard layouts

### ISSUE THREAD

**Issue by ZorkJ** [DeNederlandscheBank/name_matching#12]
![image](https://github.com/DeNederlandscheBank/name_matching/assets/31822431/57cd7d1f-4a65-4522-9a3c-85ba5d4bd207)

I am wondering what potential reason can get such ValueError.

**Comment by mnijhuis-dnb** [comment]
The reason can be that one of the tokens in the two names you are comparing, is not found in any keyboard layout that the typo distance uses. The typo distance uses the distance on a keyboard layout between the characters of the two strings. For a QWERTY layout the distance between '_error_' and '_errot_' is for instance 1, as the _t_ is just 1 key away from the _r_. To avoid this error you can either choose to use a different distance metrics instead of the typo metric, or set the option to convert all characters to ASCII characters
